---
stages:
  - clear_approval
  - build
  - test

variables:
  FULL_BUILD:
    value: "false"
    options:
      - "true"
      - "false"
    description: "Whether to run a full build, including Windows E2E"
  PENGUIN_BUILD:
    value: "false"
    options:
      - "true"
      - "false"
    description: "Whether to run a penguin_ci build"
  BUILD_LOCATION:
    value: "staging"
    options:
      - "production"
      - "staging"
    description: "Where to build"

build:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
  variables:
    JOB_TYPE: "build"
    MERGE_PROJECT: $CI_MERGE_REQUEST_PROJECT_PATH
    MERGE_PROJECT_ID: $CI_MERGE_REQUEST_PROJECT_ID
    MERGE_SOURCE_BRANCH: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    MERGE_TARGET_BRANCH: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    MERGE_REQUEST_IID: $CI_MERGE_REQUEST_IID
    MERGE_SOURCE_COMMIT: $CI_COMMIT_SHA
    SOURCE_HEAD_COMMIT: $CI_MERGE_REQUEST_SOURCE_BRANCH_SHA
    BUILD_LOCATION: "production"
  trigger:
    project: soldev/cyberdev/make_world
    branch: $MAKE_WORLD_DEFAULT_BRANCH
    strategy: depend

build (penguin ci):
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
  variables:
    JOB_TYPE: "build"
    MERGE_PROJECT: $CI_MERGE_REQUEST_PROJECT_PATH
    MERGE_PROJECT_ID: $CI_MERGE_REQUEST_PROJECT_ID
    MERGE_SOURCE_BRANCH: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    MERGE_TARGET_BRANCH: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    MERGE_REQUEST_IID: $CI_MERGE_REQUEST_IID
    MERGE_SOURCE_COMMIT: $CI_COMMIT_SHA
    SOURCE_HEAD_COMMIT: $CI_MERGE_REQUEST_SOURCE_BRANCH_SHA
    PENGUIN_BUILD: "true"
    BUILD_LOCATION: "production"
  trigger:
    project: soldev/cyberdev/make_world
    branch: $MAKE_WORLD_DEFAULT_BRANCH
    strategy: depend

build (full e2e):
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
  variables:
    JOB_TYPE: "build"
    MERGE_PROJECT: $CI_MERGE_REQUEST_PROJECT_PATH
    MERGE_PROJECT_ID: $CI_MERGE_REQUEST_PROJECT_ID
    MERGE_SOURCE_BRANCH: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    MERGE_TARGET_BRANCH: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    MERGE_REQUEST_IID: $CI_MERGE_REQUEST_IID
    MERGE_SOURCE_COMMIT: $CI_COMMIT_SHA
    SOURCE_HEAD_COMMIT: $CI_MERGE_REQUEST_SOURCE_BRANCH_SHA
    FULL_BUILD: "true"
    BUILD_LOCATION: "production"
  trigger:
    project: soldev/cyberdev/make_world
    branch: $MAKE_WORLD_DEFAULT_BRANCH
    strategy: depend

STAGING build:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
  variables:
    JOB_TYPE: "build"
    MERGE_PROJECT: $CI_MERGE_REQUEST_PROJECT_PATH
    MERGE_PROJECT_ID: $CI_MERGE_REQUEST_PROJECT_ID
    MERGE_SOURCE_BRANCH: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    MERGE_TARGET_BRANCH: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    MERGE_REQUEST_IID: $CI_MERGE_REQUEST_IID
    MERGE_SOURCE_COMMIT: $CI_COMMIT_SHA
    SOURCE_HEAD_COMMIT: $CI_MERGE_REQUEST_SOURCE_BRANCH_SHA
    BUILD_LOCATION: "staging"
  trigger:
    project: soldev/cyberdev/make_world
    branch: $MAKE_WORLD_DEFAULT_BRANCH
    strategy: depend

STAGING (penguin ci):
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
  variables:
    JOB_TYPE: "build"
    MERGE_PROJECT: $CI_MERGE_REQUEST_PROJECT_PATH
    MERGE_PROJECT_ID: $CI_MERGE_REQUEST_PROJECT_ID
    MERGE_SOURCE_BRANCH: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    MERGE_TARGET_BRANCH: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    MERGE_REQUEST_IID: $CI_MERGE_REQUEST_IID
    MERGE_SOURCE_COMMIT: $CI_COMMIT_SHA
    SOURCE_HEAD_COMMIT: $CI_MERGE_REQUEST_SOURCE_BRANCH_SHA
    PENGUIN_BUILD: "true"
    BUILD_LOCATION: "staging"
  trigger:
    project: soldev/cyberdev/make_world
    branch: $MAKE_WORLD_DEFAULT_BRANCH
    strategy: depend

STAGING (full e2e):
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
  variables:
    JOB_TYPE: "build"
    MERGE_PROJECT: $CI_MERGE_REQUEST_PROJECT_PATH
    MERGE_PROJECT_ID: $CI_MERGE_REQUEST_PROJECT_ID
    MERGE_SOURCE_BRANCH: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    MERGE_TARGET_BRANCH: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    MERGE_REQUEST_IID: $CI_MERGE_REQUEST_IID
    MERGE_SOURCE_COMMIT: $CI_COMMIT_SHA
    SOURCE_HEAD_COMMIT: $CI_MERGE_REQUEST_SOURCE_BRANCH_SHA
    FULL_BUILD: "true"
    BUILD_LOCATION: "staging"
  trigger:
    project: soldev/cyberdev/make_world
    branch: $MAKE_WORLD_DEFAULT_BRANCH
    strategy: depend


# update submodule ref in make_world when an MR is merged
update make_world:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  variables:
    JOB_TYPE: "update"
    MERGE_PROJECT: $CI_PROJECT_NAME
    MERGE_COMMIT: $CI_COMMIT_SHA
    MERGE_COMMIT_MESSAGE: $CI_COMMIT_MESSAGE
  trigger:
    project: soldev/cyberdev/make_world
    branch: $MAKE_WORLD_DEFAULT_BRANCH
    strategy: depend

remove build approval:
  stage: clear_approval
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  variables:
    JOB_TYPE: "unapprove"
    MERGE_PROJECT_ID: $CI_MERGE_REQUEST_PROJECT_ID
    MERGE_REQUEST_IID: $CI_MERGE_REQUEST_IID
  trigger:
    project: soldev/cyberdev/make_world
    branch: $MAKE_WORLD_DEFAULT_BRANCH
    strategy: depend

