[package]
name = "notatin"
version = "0.1.0"
authors = ["kimberly.stone <kimberly.stone@aon.com>"]
edition = "2018"

[dependencies]
bitflags = "1.2"
enum-primitive-derive = "0.2.1"
md5 = "0.7.0"
nom = "6"
num = "0.4"
num-traits = "0.2.14"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
winstructs = "0.3.0"
blake3 = "0.3.8"
regex = "1.5.4"
clap = "~2.33"
paste = "1.0"

[dependencies.chrono]
version = "0.4.10"
features = ["serde"]

[dev-dependencies]
criterion = "0.3"

[[bin]]
name = "reg_compare"
path = "./bin/reg_compare.rs"

[[bin]]
name = "reg_dump"
path = "./bin/reg_dump.rs"

[[bench]]
name = "my_benchmark"
path = "benches/my_benchmark.rs"
harness = false