[package]
name = "rust_parser_2"
version = "0.1.0"
authors = ["kimberly.stone <kimberly.stone@aon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6"
filetime = "0.2"
num = "0.4"
bitflags = "1.2"
thiserror = "1.0"
enum-primitive-derive = "0.2.1"
num-traits = "0.2.14"
winstructs = "0.3.0"
chrono = "^0.4"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "my_benchmark"
harness = false